---
# ------------------------------------------------------------------------
# Copyright 2020, 2022 IBM Corp. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ------------------------------------------------------------------------
- name: Building "{{ flavor }}" container image
  set_fact:
     tool_name: "image-build"
     arguments: "-f {{ flavor }} -t {{ tmp_root }}"
- import_tasks: "{{ path_to_ocp_tool }}/ansible/tasks/execute_python_tool.yml"
- name: cat result after building "{{ flavor }}" container image
  shell: "cat {{path_to_ocp_tool}}/log/{{ filename }}"
  register: logfile_out
  ignore_errors: true
- name: show stderr when rc!=0 after building "{{ flavor }}" container image
  fail:
    msg: "Building {{ flavor }} container image failed. See {{ path_to_ocp_tool}}/log/{{ filename }} for more information!"
  when: tool_out.rc != 0
- name: show result after building "{{ flavor }}" container image
  debug:
    var: logfile_out.stdout_lines
