#!/usr/bin/env python3

# ------------------------------------------------------------------------
# Copyright 2021, 2022 IBM Corp. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ------------------------------------------------------------------------

""" Ping test from worker node: Get 1st reachable ip address out of a list """

import sys
import subprocess

rtc = 'None'

if len(sys.argv) > 2:
    worker = sys.argv[1]

    for ip in sys.argv[2:]:

        sshcmd = f'ping -c 1 {ip} 2>&1 >/dev/null && echo True || echo False'
        cmd = f'ssh core@{worker} {sshcmd}'

        output = subprocess.check_output(f'{cmd}', shell=True).decode("utf-8").split()[0]
        if output == 'True':
            rtc = ip
            break

print(rtc)
