---
# ------------------------------------------------------------------------
# Copyright 2020, 2022 IBM Corp. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ------------------------------------------------------------------------

# Checking if oc tool is installed and copy it from helper node if not installed
- import_tasks: check_oc_tool.yml

# Creating temp directory for image builds
- name: Creating temp directory for image builds
  file:
    path: "{{ tmp_root }}"
    state: directory

# Installing all required packages
- name: Installing packages
  vars:
    package_list:
       - podman
       - git
       - python3
       - python3-devel
       - python3-pip
    state: "present"
  package:
    name: "{{ item }}"
    state: "{{ state }}"
  with_items:
    "{{ package_list }}"

- name: Setting up the Python virtual environment with all Python modules
  shell: "cd {{ path_to_ocp_tool }} && ./tools/venv-setup "
  register: outmsg
  ignore_errors: true
- debug: var=outmsg.stdout_lines
- name: Showing error message in case of failure
  debug: var=outmsg.stderr_lines
  failed_when: outmsg.rc != 0
  when: outmsg.rc != 0
  
- name: Activating the virtual environment
  shell: "source {{ path_to_ocp_tool }}/venv/bin/activate"
  register: outmsg
- debug: var=outmsg

# Generating config.yaml and creds.yaml and verify its parameters
- import_tasks: gen-config-creds.yml

# Verifying connection to  NFS server
- import_tasks: verify_nfs_server.yml
 
- name: Adding the cluster ip to /etc/hosts
  set_fact:
    tool_name: "ocp-etc-hosts"
    arguments: "-w"
- import_tasks: "{{ path_to_ocp_tool }}/ansible/tasks/execute_python_tool.yml"
- debug: var=tool_out

# Checking the connection to OCP4 cluster
- import_tasks: check_connection_to_ocp4_cluster.yml
