---
# ------------------------------------------------------------------------
# Copyright 2020, 2022 IBM Corp. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ------------------------------------------------------------------------

# verify NFS directories on NFS server for HDB copy and overlay share
- name: create NFS hdb directory on NFS server if NFS host name is defined
  command: ssh -o StrictHostKeyChecking=no {{ nfs_user_name }}@{{ nfs_host_name }} "mkdir -p {{ nfs_path_to_hdb_copy }}"
  when: nfs_host_name|length > 0

- name: create NFS hdb directory on helper node if NFS host name isn't defined
  command: ssh -o StrictHostKeyChecking=no {{ ocp_helper_node_user_name }}@{{ ocp_helper_node }} "mkdir -p {{ nfs_path_to_hdb_copy }}"
  when: nfs_host_name == ''

- name: create NFS overlay directory on NFS server if NFS host name is defined
  command: ssh -o StrictHostKeyChecking=no {{ nfs_user_name }}@{{ nfs_host_name }} "mkdir -p {{ nfs_path_to_overlay }}"
  when: nfs_host_name|length > 0

- name: create NFS overlay directory on helper node if NFS host name isn't defined
  command: ssh -o StrictHostKeyChecking=no {{ ocp_helper_node_user_name }}@{{ ocp_helper_node }} "mkdir -p {{ nfs_path_to_overlay }}"
  when: nfs_host_name == ''

