---
# ------------------------------------------------------------------------
# Copyright 2020, 2022 IBM Corp. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ------------------------------------------------------------------------
- name: Generating the deployment file using {{ overlay_share_name }}
  set_fact:
    tool_name: "ocp-deployment"
    arguments: "--gen-yaml -u {{ overlay_share_name }}"
- import_tasks: "{{ path_to_ocp_tool }}/ansible/tasks/execute_python_tool.yml"
- debug: var=tool_out.stdout
- set_fact: 
    deployment_file: "{{ tool_out.stdout }}"
# start deployment 
- name: Starting the deployment using deployment definition file {{ deployment_file }}
  set_fact:
    tool_name: "ocp-deployment"
    arguments: "--start -f ./{{ deployment_file }}"
- import_tasks: "{{ path_to_ocp_tool }}/ansible/tasks/execute_python_tool.yml"
- import_tasks: "{{ path_to_ocp_tool }}/ansible/tasks/wait_for_pod_running.yml"
- name: Showing the memory information of pod
  set_fact:
    tool_name: "ocp-pod-meminfo"
    arguments: ""
- import_tasks: "{{ path_to_ocp_tool }}/ansible/tasks/execute_python_tool.yml"
- debug: var=tool_out
- import_tasks: "{{ path_to_ocp_tool }}/ansible/tasks/wait_for_system_running.yml"
- name: Showing the status of the SAP system running in the pod
  set_fact:
    tool_name: "sap-system-status"
    arguments: "-w"
- import_tasks: "{{ path_to_ocp_tool }}/ansible/tasks/execute_python_tool.yml"
- debug: var=tool_out
