---
# ------------------------------------------------------------------------
# Copyright 2020, 2022 IBM Corp. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ------------------------------------------------------------------------
- name: generating the deployment file using {{ overlay_share_name }}
  shell: "cd {{path_to_ocp_tool}} && source ./venv/bin/activate && ./tools/ocp-deployment --gen-yaml -c ./config.yaml -q ./creds.yaml -u {{ overlay_share_name }}"
  register: outmsg
- debug: var=outmsg.stdout
- set_fact: 
    deployment_file: "soos-{{ nws4_sid | lower}}-{{ uuid_value }}-deployment.yaml" 
# start deployment 
- name: apply the deployment file {{ deployment_file }}
  shell: "cd {{path_to_ocp_tool}} && source ./venv/bin/activate && ./tools/ocp-deployment --start -f ./{{ deployment_file }} -c ./config.yaml -q ./creds.yaml "
- import_tasks: ../../../tasks/wait_for_pod_running.yml
- name: show pod mem info
  shell: "cd {{path_to_ocp_tool}} && source ./venv/bin/activate && ./tools/ocp-pod-meminfo -c ./config.yaml -q ./creds.yaml"
  register: out_msg
- debug: var=out_msg
- import_tasks: ../../../tasks/wait_for_system_running.yml
- name: show SAP system status
  shell: "cd {{path_to_ocp_tool}} && source ./venv/bin/activate && ./tools/sap-system-status -c ./config.yaml -q ./creds.yaml -w"
  register: outmsg
- debug: var=outmsg.stdout
