---
# ------------------------------------------------------------------------
# Copyright 2020, 2022 IBM Corp. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ------------------------------------------------------------------------
- include_vars: context.yaml
- import_tasks: "{{ path_to_ocp_tool }}/ansible/tasks/oc-user-login.yml"
- name: Getting image list from OCP Cluster Registry
  command: oc get imagestream 
  register: out_image_stream
- set_fact:
     out_lines: "{{ out_image_stream.stdout_lines }}"
     image_names: []
- set_fact:
     image_names: "{{ image_names + [item.split(' ')[0]]  }}"
  with_items: "{{ out_lines }}"
- fail:
     msg: "Image {{ item.value.names.short }} missing in local OpenShift Cluster Registry"
  when:
     item.value.names.short not in image_names
  with_dict: "{{ cf.images }}"
