---
# ------------------------------------------------------------------------
# Copyright 2020 IBM Corp. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ------------------------------------------------------------------------

######################
# build LPAR parameter
######################

# Path to the directory of the clone of this repository on the build LPAR
path_to_ocp_tool: <github_clone_dir>

# Directory under which the build contexts for image build are assembled
tmp_root: /data/tmp

# installs packages with ansible package module and state present
package_state: present

# generate config file for automatic tools script execution with template config.j2.template
template_config_file: config.j2.template


#############################
# OpenShift cluster parameter
#############################

# Domain name of the Red Hat OpenShift Container Platform (OCP) cluster - used for "oc" operations
# The build LPAR must be able to connect to api.<ocp_cluster_domain>
ocp_cluster_domain: <ocp4-domain-name>

# Password of the kubeadmin user in OCP cluster
admin_psw: <kubeadmin-password>

# User in OCP cluster which is used for "oc" operations
oc_user: <ocp4-userid>

# Password of ocp_user in OCP cluster
oc_psw: <ocp4-user-password>

# Name of the OCP project which will be created for the SAP workload (e.g. my-sap-project)
oc_project_name: <ocp4_project_name_for_SAP>


################################
# NetWeaver or S/4HANA parameter
################################

# Host on which the original SAP NetWeaver or SAP S/4HANA system is installed
# The SAP instance profile must also have this hostname in its name
host_nws4: <reference_system_hostname>

# User on host_nws4 which is used for ssh and rsync operations (needs root permissions)
host_user_nws4: root

# SAP system ID of the original SAP NetWeaver or SAP S/4HANA system (upper case)
nws4_sid: <AppServer_SID>

# SAP system ID of the original SAP NetWeaver or SAP S/4HANA system (lower case)
# Use lower case "sid" to generate deployment file name
nws4_sid_lower_case: <AppServer_sid_lower_case>

# SAP system ID of the original SAP HANA system (lower case)
# Use lower case "sid" to generate deployment file name
hdb_sid_deployment: <HANA_sid_lower_case>


###############
# NFS parameter
###############

# Host on which the NFS server is running
nfs_host: <NFS_server_hostname>

# User on nfs.host which is used for ssh and rsync operations (needs root permissions)
# Password-less access for this user from build LPAR to NFS server must be configured
nfs_user: root

# Path on nfs_host where directories {data,log} of the original HANA system are copied to
path_to_hdb_copy: <NFS_server_export_dir_for_hdb>

# Path on nfs_host under which overlay file systems for container instances are created
path_to_overlay: <NFS_server_export_dir_for_overlay>

##################
# GitHub parameter
##################

# GitHub repository URL for project containerization-for-sap-s4hana
github_repo_url: https://github.com/IBM/containerization-for-sap-s4hana.git

