---
# ------------------------------------------------------------------------
# Copyright 2020 IBM Corp. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ------------------------------------------------------------------------
- name: Login as user "{{oc_user}}" to OCP cluster
  shell: "oc login --insecure-skip-tls-verify=true https://api.{{ocp_cluster_domain}}:6443 -u {{oc_user}} -p {{oc_psw}}"
  register: login_ocp_msg
- debug: var=login_ocp_msg.stdout
  


