---
# ------------------------------------------------------------------------
# Copyright 2020, 2022 IBM Corp. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ------------------------------------------------------------------------
# import vars from context.yaml file
- include_vars: context.yaml

- import_tasks: "{{ path_to_ocp_tool }}/ansible/tasks/oc-user-login.yml"
  
- set_fact:
    oc_project: "{{ cf.ocp.project }}"
- name: Checking if the project "{{ cf.ocp.project }}"exists already
  shell: "oc get projects" 
  register: oc_all_projects

- name: Creating project "{{ cf.ocp.project }}" if it does not exist
  shell: "oc new-project {{cf.ocp.project}}"
  register: outmsg
  when: oc_project not in oc_all_projects.stdout
- name: show new-project
  debug: var=outmsg

- name: Setting the project
  shell: "oc project {{cf.ocp.project}}"
- name: Getting the service account
  shell: "oc get serviceaccount"
  register: outmsg
- debug: var=outmsg.stdout
  when: outmsg.rc==0
- debug:
    msg: "outmsg.stderr"
  failed_when: outmsg.rc != 0

- import_tasks: "{{ path_to_ocp_tool }}/ansible/tasks/oc-admin-login.yml"
  
- name: Enabling the Image Registry default route, patch the Image Registry Operator
  shell: "oc patch configs.imageregistry.operator.openshift.io/cluster --type merge -p '{\"spec\":{\"defaultRoute\":true}}'"
  register: r_msg
- name: show Image Registry default route
  debug: var=r_msg

- name: Adding permissions for ocp project
  shell: "oc adm policy add-scc-to-group anyuid 'system:serviceaccounts:{{cf.ocp.project}}'"
  register: out_p
- name: Showing permission settings
  debug: var=out_p.stdout

- name: Generating the ocp service-account
  set_fact:
    tool_name: "ocp-service-account-gen"
    arguments: "-o {{path_to_ocp_tool}}/{{cf.ocp.sa.file}} -w"
- import_tasks: "{{ path_to_ocp_tool }}/ansible/tasks/execute_python_tool.yml"
- name: Showing result after service account generation
  debug: var=tool_out.stdout

- import_tasks: "{{ path_to_ocp_tool }}/ansible/tasks/oc-admin-login.yml"

- name: Adding the required security context constraints to the service account
  shell: "oc adm policy add-scc-to-user hostmount-anyuid system:serviceaccount:{{cf.ocp.project}}:{{cf.ocp.sa.name}}"
  register: out_msg
- name: Showing result after add-scc-to-user
  debug: var=out_msg
  
# generate secret for Distributed Reference System after OCP project is checked, created
- include_tasks: generate_ocp_secret.yml
  when: cf.refsys.nws4.host.name != cf.refsys.hdb.host.name

- name: Verifying configuration settings of config.yaml and creds.yaml
  set_fact:
    tool_name: "verify-config"
    arguments: "-w"
- import_tasks: "{{ path_to_ocp_tool }}/ansible/tasks/execute_python_tool.yml"
- debug: var=tool_out.stdout_lines
- name: check missing verify configuration parameters
  debug: var=tool_out.stderr_lines
  failed_when: tool_out.rc != 0
  when: tool_out.rc != 0

# Checking security context constraints, checking worker nodes
- name: Verifying ocp settings
  set_fact:
    tool_name: "verify-ocp-settings"
    arguments: "-w"
- import_tasks: "{{ path_to_ocp_tool }}/ansible/tasks/execute_python_tool.yml"
- debug: var=tool_out.stdout_lines
- name: Checking if ocp settings are correct
  debug: var=tool_out.stderr_lines
  failed_when: tool_out.rc != 0
  when: tool_out.rc != 0
