---
# ------------------------------------------------------------------------
# Copyright 2020, 2022 IBM Corp. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ------------------------------------------------------------------------
- name: creating HANA DB overlay share on the NFS server
  shell: "cd {{path_to_ocp_tool}} && source ./venv/bin/activate && ./tools/nfs-overlay-setup -c ./config.yaml -q ./creds.yaml"
  register: uuid_status
- debug: var=uuid_status.stdout
- name: store uuid for the deployment file
  set_fact: 
    overlay_share_name: "{{ uuid_status.stdout }}"
    uuid_value: "{{ uuid_status.stdout.split('-') | last }}"
