#!/usr/bin/env python3

# ------------------------------------------------------------------------
# Copyright 2021, 2022 IBM Corp. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ------------------------------------------------------------------------

""" Configuration management """


try:
    # Global modules

    import yaml

    # Local modules

    from modules.args     import getCommonArgsParser
    from modules.config   import Config
    from modules.context  import getContext
    from modules.nestedns import nestedNsToObj
    from modules.startup  import startup

except ModuleNotFoundError as mnfex:
    from modules.exceptions import setExceptHook
    setExceptHook()
    raise mnfex


# Functions

def _getArgs():
    """ Get command line arguments """
    parser = getCommonArgsParser(
        'Configuration management'
    )

    parser.add_argument(
        '-n',
        '--new',
        required = False,
        action   = 'store_true',
        help     = "Create a new configuration file"
    )

    parser.add_argument(
        '-e',
        '--edit',
        required = False,
        action   = 'store_true',
        help     = "Change configuration in an existing configuration file"
    )

    parser.add_argument(
        '-d',
        '--dump',
        required = False,
        action   = 'store_true',
        help     = "Dump configuration to stdout"
    )

    parser.add_argument(
        '--non-interactive',
        required = False,
        action   = 'store_true',
        help     = "Perform '-n' and '-e' non-interactively"
                   ' (reading values from environment)'
    )

    parser.add_argument(
        '-s',
        '--suppress-descriptions',
        required = False,
        action   = 'store_true',
        help     = "Don't show detailed descriptions during edit"
    )

    return parser.parse_args()


# ----------------------------------------------------------------------

def _main():

    ctx = getContext(_getArgs(), withCreds=True, withConfig=False)

    if ctx.ar.new:
        config = Config(ctx, create=True, failOnDiscoveryError=False)
    else:
        config = Config(ctx, create=False, failOnDiscoveryError=False)

    if ctx.ar.new:
        config.create(ctx.ar.suppress_descriptions)

    elif ctx.ar.edit:
        config.edit(ctx.ar.suppress_descriptions)

    elif ctx.ar.dump:
        print(yaml.dump(nestedNsToObj(config.get())))

    else:
        print('\nUse option\n\n'
              "  '-n' to create a new configuration file\n"
              "  '-e' to edit an existing configuration file\n"
              "  '-d' to dump an existing configuration file\n"
              "  '-h' to get more help\n\n"
              "NEVER CHANGE FILE 'config.yaml.template'"
              " - OTHERWISE THIS TOOL WON'T WORK AS EXPECTED\n")


# ----------------------------------------------------------------------

if __name__ == '__main__':
    startup(_main)
