#!/usr/bin/env python3

# ------------------------------------------------------------------------
# Copyright 2020 IBM Corp. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ------------------------------------------------------------------------

""" Automated build, push and deploy """

# Global modules

import sys

# Local modules

from modules.args    import getCommonArgsParser
from modules.command import CmdShell
from modules.config  import (
    getConfig,
    getFlavors
)
from modules.logger  import setupLogging
from modules.tools   import ocLogin

# Functions


def _getArgs():
    """ Get command line arguments """
    parser = getCommonArgsParser(
        'Automated build, push and deploy'
    )

    # pylint: disable=bad-whitespace

    parser.add_argument(
        '-y',
        '--hdb-copy',
        required = False,
        action   = 'store_true',
        help     = "Copy HANA DB snapshot to NFS server"
    )
    parser.add_argument(
        '-b',
        '--build-images',
        required = False,
        action   = 'store_true',
        help     = "Build images"
    )
    parser.add_argument(
        '-p',
        '--push-images',
        required = False,
        action   = 'store_true',
        help     = "Push images to local OCP cluster registry"
    )
    parser.add_argument(
        '-o',
        '--setup-overlay-share',
        required = False,
        action   = 'store_true',
        help     = "Setup overlay share"
    )
    parser.add_argument(
        '-u',
        '--overlay-uuid',
        metavar  = '<overlay-uuid>',
        required = False,
        help     = "UUID of overlay share for options '-d' and '-t'"
    )
    parser.add_argument(
        '-l',
        '--list-overlay-shares',
        required = False,
        action   = 'store_true',
        help     = "List existing overlay shares"
    )
    parser.add_argument(
        '-t',
        '--tear-down-overlay-share',
        required = False,
        action   = 'store_true',
        help     = "Tear down overlay share specified with option '-u'"
    )
    parser.add_argument(
        '-d',
        '--create-deployment-file',
        required = False,
        action   = 'store_true',
        help     = "Create deployment file"
    )
    parser.add_argument(
        '-s',
        '--start-deployment',
        required = False,
        action   = 'store_true',
        help     = "Start deployment on OCP cluster"
    )
    parser.add_argument(
        '-x',
        '--stop-deployment',
        required = False,
        action   = 'store_true',
        help     = "Stop deployment on OCP cluster"
    )
    parser.add_argument(
        '-a',
        '--execute-all',
        required = False,
        action   = 'store_true',
        help     = "Execute all actions (except '-t', '-l' and '-x')"
    )
    parser.add_argument(
        '-r',
        '--execute-rest',
        required = False,
        action   = 'store_true',
        help     = "Start with specified action "
                   "and execute all subsequent actions in automation process."
    )
    return parser.parse_args()


def _genHeader(header, lineChar):
    """ Generate header string (generic) """
    return lineChar*60+'\n'+header+'\n'+lineChar*60


def _genHeader1(header):
    """ Generate header string (level 1 header) """
    return _genHeader(header, '=')


def _genHeader2(header):
    """ Generate header string (level 2 header) """
    return _genHeader(header, '-')


def getOverlayUuid(args, overlayUuid):
    """ Get overlay UUID from parameter or cli argument.
        Exit, if no overlay UUID can be determined """
    if not overlayUuid:
        if args.overlay_uuid:
            overlayUuid = args.overlay_uuid
        else:
            print("Please specify an overlay share UUID via option '-u'")
            sys.exit(1)
    return overlayUuid


def _copyHdb(config, cliCommonArgs):
    """ Copy snapshot of HANA DB to NFS server (automation option) """
    print(_genHeader1(f"Copying snapshot of HANA DB '{config.flavor.hdb.sid}'"
                      f" to NFS server '{config.nfs.host}'"))
    cmd = f'time {config.repo.root}/tools/nfs-hdb-copy'
    cmd += cliCommonArgs
    CmdShell().run(cmd)


def _buildImages(config, cliCommonArgs):
    """ Build images for all flavors (automation option) """
    for flavor in getFlavors(config):
        print(_genHeader1(f"Building image for flavor '{flavor}'"))
        cmd = f'time {config.repo.root}/tools/image-build'
        cmd += f' -f {flavor}'
        cmd += cliCommonArgs
        CmdShell().run(cmd)


def _pushImages(config, cliCommonArgs):
    """ Push images for all flavors to OCP (automation option) """
    for flavor in getFlavors(config):
        print(_genHeader1(f"Pushing image for flavor '{flavor}'"))
        cmd = f'time {config.repo.root}/tools/image-push'
        cmd += f' -f {flavor}'
        cmd += cliCommonArgs
        CmdShell().run(cmd)


def _setupOverlayShare(config, cliCommonArgs):
    """ Setup an overlay share on NFS server (automation option) """
    print(_genHeader1('Setting up overlay share'))
    cmd = f'time {config.repo.root}/tools/nfs-overlay-setup'
    cmd += cliCommonArgs
    overlayUuid = CmdShell().run(cmd).out
    print(overlayUuid)
    return overlayUuid


def _createDeploymentFile(config, overlayUuid, cliCommonArgs):
    """ Create deployment file (automation option) """
    assert overlayUuid
    deploymentFile = config.ocp.deploymentFileName
    print(_genHeader1(f"Creating deployment file '{deploymentFile}'"
                      f" with overlay share '{overlayUuid}'"))
    cmd = f'time {config.repo.root}/tools/ocp-deployment-gen'
    cmd += f' -u {overlayUuid}'
    cmd += f' -o {deploymentFile}'
    cmd += cliCommonArgs
    print(CmdShell().run(cmd).out)


def _startDeployment(config):
    """ Start deployment using deployment file (automation option) """
    deploymentFile = config.ocp.deploymentFileName
    print(_genHeader1(f"Starting deployment using file '{deploymentFile}'"))
    ocLogin(config)
    CmdShell().run(f'time oc apply -f {deploymentFile}')


def _listOverlayShares(config, cliCommonArgs):
    """ List all overlay shares on NFS server (manual option) """
    print(_genHeader1('List of existing overlay shares:'))
    cmd = f'time {config.repo.root}/tools/nfs-overlay-list'
    cmd += cliCommonArgs
    print(CmdShell().run(cmd).out)


def _tearDownOverlayShare(config, overlayUuid, cliCommonArgs):
    """ Tear down an overlay share on NFS server (manual option) """
    assert overlayUuid
    print(_genHeader1(f'Tearing down overlay share {overlayUuid}'))
    cmd = f'time {config.repo.root}/tools/nfs-overlay-teardown'
    cmd += f' -u {overlayUuid}'
    cmd += cliCommonArgs
    CmdShell().run(cmd)


def _stopDeployment(config):
    """ Stop deployment using deployment file (manual option) """
    deploymentFile = config.ocp.deploymentFileName
    print(_genHeader1(f"Stopping deployment using file '{deploymentFile}'"))
    ocLogin(config)
    CmdShell().run(f'time oc delete -f {deploymentFile}')

# ----------------------------------------------------------------------


def _main():
    args = _getArgs()

    setupLogging(args)

    config = getConfig(args.config_file, True)

    # Common arguments for all called commands

    cliCommonArgs = ''
    cliCommonArgs += f' -c {args.config_file}'
    cliCommonArgs += f' -g {args.logfile_dir}'
    cliCommonArgs += f' -v {args.loglevel}'

    if args.log_to_terminal:
        cliCommonArgs += ' -w'

    overlayUuid = None

    # ↓↓↓ AUTOMATION OPTIONS ↓↓↓

    # Copy snapshot of HANA

    if args.execute_all or args.hdb_copy:
        args.execute_all = args.execute_all or args.execute_rest
        _copyHdb(config, cliCommonArgs)

    # Build images

    if args.execute_all or args.build_images:
        args.execute_all = args.execute_all or args.execute_rest
        _buildImages(config, cliCommonArgs)

    # Push images

    if args.execute_all or args.push_images:
        args.execute_all = args.execute_all or args.execute_rest
        _pushImages(config, cliCommonArgs)

    # Setup overlay share

    if args.execute_all or args.setup_overlay_share:
        args.execute_all = args.execute_all or args.execute_rest
        overlayUuid = _setupOverlayShare(config, cliCommonArgs)

    # Create deployment YAML file

    if args.execute_all or args.create_deployment_file:
        args.execute_all = args.execute_all or args.execute_rest
        _createDeploymentFile(config, getOverlayUuid(
            args, overlayUuid), cliCommonArgs)

    # Start deployment

    if args.execute_all or args.start_deployment:
        args.execute_all = args.execute_all or args.execute_rest
        _startDeployment(config)

    # ↑↑↑ AUTOMATION OPTIONS ↑↑↑

    # ↓↓↓ MANUAL OPTIONS ↓↓↓

    # List existing overlay shares

    if args.list_overlay_shares:
        _listOverlayShares(config, cliCommonArgs)

    # Tear down overlay share

    if args.tear_down_overlay_share:
        _tearDownOverlayShare(config, getOverlayUuid(
            args, overlayUuid), cliCommonArgs)

    # Stop deployment

    if args.stop_deployment:
        _stopDeployment(config)

    # ↑↑↑ MANUAL OPTIONS ↑↑↑

# ----------------------------------------------------------------------


if __name__ == "__main__":
    _main()
    sys.exit(0)
