#!/usr/bin/env python3

# ------------------------------------------------------------------------
# Copyright 2020, 2021 IBM Corp. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ------------------------------------------------------------------------

""" Push a container image of a given flavor to the internal cluster registry """


# Global modules

import sys


# Local modules

from modules.args    import (
    getCommonArgsParser,
    addArgImageFlavor
)
from modules.command import CmdShell
from modules.context import getContext
from modules.ocp     import podmanOcpRegistryLogin


# Functions

def _getArgs():
    """ Get command line arguments """
    parser = getCommonArgsParser(
        'Push a container image of a given flavor to the internal cluster registry'
    )

    addArgImageFlavor(parser)

    return parser.parse_args()


def _tagImage(ctx, flavor):
    names = getattr(ctx.cf.images, flavor).names
    CmdShell().run(f'podman tag {names.local} {names.ocp}')


def _pushImage(ctx, flavor):
    names = getattr(ctx.cf.images, flavor).names
    cmd = 'podman push'
    cmd += ' --tls-verify=false'
    cmd += f' {names.ocp}'
    CmdShell().run(cmd)


# ----------------------------------------------------------------------

def _main():

    ctx = getContext(_getArgs())

    podmanOcpRegistryLogin(ctx)

    _tagImage(ctx, ctx.ar.image_flavor)

    _pushImage(ctx, ctx.ar.image_flavor)


# ----------------------------------------------------------------------

if __name__ == '__main__':
    try:
        _main()
    except KeyboardInterrupt:
        print()
    sys.exit(0)
