#!/usr/bin/env python3

# ------------------------------------------------------------------------
# Copyright 2020, 2022 IBM Corp. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ------------------------------------------------------------------------

""" Tear down overlay file system on NFS server """


try:
    # Global modules

    # None

    # Local modules

    from modules.args     import (
        addArgOverlayUuid,
        getCommonArgsParser
    )
    from modules.context  import getContext
    from modules.nfstools import Overlays
    from modules.startup  import startup

except ModuleNotFoundError as mnfex:
    from modules.exceptions import setExceptHook
    setExceptHook()
    raise mnfex


# Functions

def _getArgs():
    """ Get command line arguments """
    parser = getCommonArgsParser(
        'Tear down overlay file system on NFS server'
    )

    addArgOverlayUuid(parser)

    return parser.parse_args()


# ----------------------------------------------------------------------

def _main():

    ctx = getContext(_getArgs())

    overlay = Overlays(ctx).find(ctx.ar.overlay_uuid)

    print(f"Deleting overlay share '{overlay}'")

    overlay.delete()


# ----------------------------------------------------------------------

if __name__ == '__main__':
    startup(_main)
