#!/usr/bin/env python3

# ------------------------------------------------------------------------
# Copyright 2020 IBM Corp. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ------------------------------------------------------------------------

""" Copy an SAP HANA DB snapshot to the NFS server """

# Global modules

import sys

# Local modules

from modules.args     import getCommonArgsParser
from modules.command  import CmdSsh
from modules.config   import getConfig
from modules.logger   import setupLogging
from modules.nfsTools import (
    getHdbCopyBase,
    getHdbSubDirs
)
from modules.tools    import getNumRunningSapProcs


# Functions


def _getArgs():
    """ Get command line arguments """
    parser = getCommonArgsParser(
        'Copy an SAP HANA DB snapshot the NFS server'
    )

    return parser.parse_args()


def _hdbIsStopped(config):
    return getNumRunningSapProcs(config, 'hdb') == '0'

# ----------------------------------------------------------------------


def _main():

    args = _getArgs()
    setupLogging(args)

    config = getConfig(args.config_file, True)
    hdbSid = config.flavor.hdb.sid.upper()
    cmdSsh = CmdSsh(config.nfs.host, config.nfs.user)

    if _hdbIsStopped(config):
        for subDir in getHdbSubDirs():
            sourceDir = f"{config.flavor.hdb.user}@{config.flavor.hdb.host}" \
                        f":{config.flavor.hdb.base}/{subDir}/{hdbSid}/*"
            targetDir = f"{getHdbCopyBase(config)}/{subDir}/{hdbSid}"
            cmdSsh.run(f"mkdir -p '{targetDir}'")
            print(f"Copying '{sourceDir}' to '{targetDir}' on host '{config.nfs.host}'")
            cmdSsh.run(f"rsync -avr '{sourceDir}' '{targetDir}'")
    else:
        print(f"Error: HANA Database '{hdbSid}' is running on host {config.flavor.hdb.host}.\n"
              f"Stop the database then restart the nfs-hdb-copy step.")
        sys.exit(1)

# ----------------------------------------------------------------------


if __name__ == "__main__":
    _main()
    sys.exit(0)
