#!/usr/bin/env python3

# ------------------------------------------------------------------------
# Copyright 2020, 2021 IBM Corp. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ------------------------------------------------------------------------

""" Verify parameter settings in configuration YAML file """


# Global modules

import sys


# Local modules

from modules.args    import getCommonArgs
from modules.context import getContext
from modules.fail    import fail
from modules.verify  import Verify


# Functions


# ----------------------------------------------------------------------

def _main():

    ctx = getContext(getCommonArgs(
        'Verify parameter settings in configuration YAML file'
    ))
    print('-'*72)
    print(f"Verifying configuration parameters in file '{ctx.ar.config_file}'")
    print('-'*72)

    if not Verify(ctx).verify():
        print('-'*72)
        fail('VERIFICATION ERRORS OCCURED - SEE ABOVE MESSAGES FOR MORE DETAILS\n')

    print('-'*72)
    print('Verification successful.\n')


# ----------------------------------------------------------------------

if __name__ == '__main__':
    try:
        _main()
    except KeyboardInterrupt:
        print()
    sys.exit(0)
